export const APP_ACTIONS = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_RESOLVED: 'FETCH_DATA_RESOLVED',
  FETCH_DATA_RESOLVING: 'FETCH_DATA_RESOLVING',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_THEME: 'FETCH_THEME',
  FETCH_THEME_RESOLVED: 'FETCH_THEME_RESOLVED',
  FETCH_THEME_RESOLVING: 'FETCH_THEME_RESOLVING',
};
